// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - CoreRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface CoreRoot : GPBRootObject
@end

#pragma mark - SendTransactionRequest

typedef GPB_ENUM(SendTransactionRequest_FieldNumber) {
  SendTransactionRequest_FieldNumber_RawTransaction = 1,
  SendTransactionRequest_FieldNumber_AllowHighFees = 2,
  SendTransactionRequest_FieldNumber_BypassLimits = 3,
};

@interface SendTransactionRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *rawTransaction;

@property(nonatomic, readwrite) BOOL allowHighFees;

@property(nonatomic, readwrite) BOOL bypassLimits;

@end

#pragma mark - SendTransactionResponse

typedef GPB_ENUM(SendTransactionResponse_FieldNumber) {
  SendTransactionResponse_FieldNumber_TransactionId = 1,
};

@interface SendTransactionResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionId;

@end

#pragma mark - GetTransactionRequest

typedef GPB_ENUM(GetTransactionRequest_FieldNumber) {
  GetTransactionRequest_FieldNumber_Id_p = 1,
};

@interface GetTransactionRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@end

#pragma mark - GetTransactionResponse

typedef GPB_ENUM(GetTransactionResponse_FieldNumber) {
  GetTransactionResponse_FieldNumber_Transaction = 1,
};

@interface GetTransactionResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *transaction;

@end

#pragma mark - GetBestBlockHeightRequest

@interface GetBestBlockHeightRequest : GPBMessage

@end

#pragma mark - GetBestBlockHeightResponse

typedef GPB_ENUM(GetBestBlockHeightResponse_FieldNumber) {
  GetBestBlockHeightResponse_FieldNumber_Height = 1,
};

@interface GetBestBlockHeightResponse : GPBMessage

@property(nonatomic, readwrite) uint32_t height;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
